version: '3'
services:
  web:
    image: apache2
    build: .
    container_name: bubbles_walnutbrains_org
    environment:
      VIRTUAL_HOST: bubbles.walnutbrains.org 
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: bubbles.walnutbrains.org 
      LETSENCRYPT_EMAIL: smcgarril@gmail.com
    restart: always
    ports:
      - "8082:80"
    expose:
      - 80
networks:
  default:
    external:
      name: nginx-proxy
